# Tarea 1 Geodinamica 201520 - Luis Alejandro Rodríguez Parra 
Punto 2: Recall that the Hawaiian Island chain is being formed as the Pacific plate passes over a hotspot. Suppose that Mauna Loa volcano will become extinct when it moves 100 km away from its present location over the hotspot. (a) How long will this take? (b) Eventually, the first of the islands in the chain will hit some type of landmass. Estimate when and where that will happen. 

Para resolver el problema primero tenemos que encontrar la velocidad de movimiento de la Placa del Pacifico respecto al hotspot. En este caso vamos a utilizar un polo de Euler Absoluto ubicado en latitud y longitud (- 61.7°, 97.2°) y que cuenta con velocidad angurar 9.67 x 10-7 deg/yr. Tambien utilizamos las cordenadas actuales del volcan Mauna Loa en latitud y longitud (19.46°, -155.59°).

In [33]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [34]:
# Definimos: R = radio de la tierra (cm), la = latitud del punto (º), lo = longitud del punto (º)
# pla = latitud polo (º), plo = longitud polo (º), w = velocidad angular (deg/yr)
R = 6370.8E5
la = 19.46
lo = -155.59
pla = -61.7
plo = 97.2
w = 9.67E-7

In [35]:
#Convertimos las unidades de las cordenadas y la velocidad angular a radianes
DR = pi/180
lar = la*DR
lor = lo*DR
plar = pla*DR
plor = plo*DR
wr = w*DR

In [36]:
#Ya que tenemos las coordenadas en radianes necesitamos converir los datos a cordenadas cartesianes globales
X =  (cos(lar)*cos(lor)*R, cos(lar)*sin(lor)*R, sin(lar)*R)
PX = (cos(plar)*cos(plor)*wr, cos(plar)*sin(plor)*wr, sin(plar)*wr)

La anterior conversión de coordenadas se realizo siguiendo los datos de http://stackoverflow.com/questions/1185408/converting-from-longitude-latitude-to-cartesian-coordinates

In [37]:
#Realizamos el producto cruz entre los dos vectores, para obtener la velocidad de movimiento
V = cross(PX,X)
print V

[-2.00406517  8.34120443  4.59110512]


Ahora necesitamos realizar la conversión de coordenadas cartesianas globales a coordenadas locales, para esto necesitamos realizar una matriz de transformación. En este caso nosotros estamos utilizando la propuesta por (Cox & Hart, 1986)

In [38]:
#Definimos la matriz de rotación para convertir las cordenadas globales a cordenadas locales
TR = zeros((3,3))
TR[0,0] = -sin(lar)*cos(lor)
TR[0,1] = -sin(lar)*sin(lor)
TR[0,2] = cos(lar)
TR[1,0] = -sin(lor)
TR[1,1] = cos(lor)
TR[1,2] = 0
TR[2,0] = -cos(lar)*cos(lor)
TR[2,1] = -cos(lar)*sin(lor)
TR[2,2] = -sin(lar)
print TR

[[ 0.30336904  0.13767815  0.9428743 ]
 [ 0.41326337 -0.91061155  0.        ]
 [ 0.85859223  0.38965541 -0.33314869]]


In [39]:
#Multiplicamos la matriz de transformación por el vector de velocidad ya encontrado, y obtenemos
#la velocidad VF(Norte,Este,Up)
Vt = np.matrix(V).T
VF = TR*Vt
print VF

[[  4.86926530e+00]
 [ -8.42380379e+00]
 [  4.44089210e-16]]


Las indicaciones generales se tomaron de: http://eqseis.geosc.psu.edu/~cammon/HTML/UsingMATLAB/PDF/ML2%20PlateVelocity.pdf

In [42]:
#La magnitud de la velocidad es en cm/yr
y = sqrt(VF[0,0]**2 + VF[1]**2 + VF[2]**2)
print "La magnitud de la velocidad es", y, "Cm/año"

La magnitud de la velocidad es [[ 9.72986201]] Cm/año


Ahora, si ausumimos que la velocidad de movimiento se va a manter constante tanto en magnitud como en dirección, podemos encontrar el tiempo que va atardar el moverse 100km. Es decir asumimos que el movimiento va a ser constante en el tiempo.

In [43]:
# Encontramos el tiempo que va a tardar en moverse 100km, con la relación t=d/v, ya conocemos la magnitud de la v
d = 100E5
t = d/y
print "El tiempo que va a tardar Mauna Loa en moverse 100km es:", t, "años"

El tiempo que va a tardar Mauna Loa en moverse 100km es: [[ 1027763.80449934]] años
